# Generated by Django 5.1.15 on 2026-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "llm_base_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="LLM Base URL",
                    ),
                ),
                (
                    "llm_api_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="LLM API Key",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="LLM 模型"
                    ),
                ),
                (
                    "embedding_mode",
                    models.CharField(
                        blank=True,
                        choices=[("local", "本地(local)"), ("remote", "远程(remote)")],
                        default="",
                        max_length=20,
                        verbose_name="Embedding 模式",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="本地 Embedding 模型",
                    ),
                ),
                (
                    "llm_embedding_base_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="远程 Embedding Base URL",
                    ),
                ),
                (
                    "llm_embedding_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="远程 Embedding 模型",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "模型配置",
                "verbose_name_plural": "模型配置",
            },
        ),
    ]
