# Generated by Django 5.1.15 on 2026-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfig",
            name="vision_api_key",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="多模态 API Key"
            ),
        ),
        migrations.AddField(
            model_name="aiconfig",
            name="vision_base_url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="多模态 Base URL"
            ),
        ),
        migrations.AddField(
            model_name="aiconfig",
            name="vision_model",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="多模态模型"
            ),
        ),
    ]
