# Generated by Django 5.1.15 on 2026-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("requirement", "需求分析"),
                    ("planning", "项目计划"),
                    ("architecture", "架构设计"),
                    ("developing", "开发实施"),
                    ("delivery", "项目交付"),
                    ("operation", "项目运营"),
                ],
                default="requirement",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
