# Generated by Django 5.1.15 on 2026-08-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0002_bug"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug",
            name="module",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="业务模块"
            ),
        ),
        migrations.CreateModel(
            name="BugImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="bugs/", verbose_name="图片")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="testing.bug",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺陷图片",
                "verbose_name_plural": "缺陷图片",
                "ordering": ["-created_at"],
            },
        ),
    ]
