# Generated by Django 5.1.15 on 2026-08-11 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frontend_stack",
                    models.CharField(max_length=200, verbose_name="前端技术栈"),
                ),
                (
                    "backend_stack",
                    models.CharField(max_length=200, verbose_name="后端技术栈"),
                ),
                (
                    "base_framework",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "无（自研）"),
                            ("ruoyi-vue-plus", "Ruoyi-Vue-Plus"),
                            ("smart-admin", "Smart-Admin"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="框架底座",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("postgresql", "PostgreSQL")],
                        default="mysql",
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "design_doc",
                    models.TextField(
                        blank=True, default="", verbose_name="架构概设文档(markdown)"
                    ),
                ),
                (
                    "db_sql",
                    models.TextField(
                        blank=True, default="", verbose_name="数据库设计 SQL"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arch_designs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "架构设计",
                "verbose_name_plural": "架构设计",
                "ordering": ["-created_at"],
            },
        ),
    ]
