# Generated by Django 5.1.15 on 2026-08-12 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages", models.JSONField(default=list, verbose_name="对话消息")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "design",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_thread",
                        to="architecture.architecturedesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "架构设计对话",
                "verbose_name_plural": "架构设计对话",
            },
        ),
    ]
