# Generated by Django 5.1.15 on 2026-09-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture", "0002_architecturechat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architecturedesign",
            name="base_framework",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "无（自研）"),
                    ("ruoyi-vue-plus", "Ruoyi-Vue-Plus（5.x）"),
                    ("smart-admin", "Smart-Admin"),
                ],
                default="",
                max_length=50,
                verbose_name="框架底座",
            ),
        ),
    ]
