# Generated by Django 5.1.15 on 2026-08-11 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_project_status"),
        ("requirements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_members",
                    models.PositiveIntegerField(verbose_name="计划人数"),
                ),
                ("launch_date", models.DateField(verbose_name="计划上线时间")),
                ("plan_content", models.TextField(verbose_name="计划内容(markdown)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="projects.project",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans",
                        to="requirements.requirement",
                        verbose_name="依据需求文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目计划",
                "verbose_name_plural": "项目计划",
                "ordering": ["-created_at"],
            },
        ),
    ]
