# Generated by Django 5.1.15 on 2026-08-11 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0002_projectplan_name_projectplanmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectplan",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name="计划开始时间"),
            preserve_default=False,
        ),
    ]
