# Generated by Django 5.1.15 on 2026-08-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_planning", "0003_projectplan_start_date"),
        ("projects", "0002_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="任务名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="任务描述"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="业务模块"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("simple", "简单"),
                            ("medium", "中等"),
                            ("hard", "复杂"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "estimated_days",
                    models.FloatField(default=0, verbose_name="预估工期(人日)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("executing", "执行中"),
                            ("done", "已完成"),
                            ("blocked", "阻塞"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="计划开始"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="计划完成"),
                ),
                (
                    "depends",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="前置依赖"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project_planning.projectplan",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "开发任务",
                "verbose_name_plural": "开发任务",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
