# Generated by Django 5.1.15 on 2026-08-14 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("iteration", "迭代需求"),
                            ("optimization", "优化需求"),
                            ("change", "业务变更"),
                            ("feedback", "用户反馈"),
                        ],
                        default="iteration",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="内容/描述"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("evaluating", "待评估"),
                            ("accepted", "已接受"),
                            ("scheduled", "已安排"),
                            ("online", "已上线"),
                            ("closed", "已关闭"),
                        ],
                        default="evaluating",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "requestor",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="提出人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "运营记录",
                "verbose_name_plural": "运营记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="YYYY-MM", max_length=7, verbose_name="月份"
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        choices=[
                            ("renewal", "续期/续费"),
                            ("satisfaction", "满意度"),
                            ("active_users", "活跃用户"),
                            ("custom", "自定义"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="指标",
                    ),
                ),
                ("value", models.FloatField(default=0, verbose_name="数值")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="说明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_metrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "运营指标",
                "verbose_name_plural": "运营指标",
                "ordering": ["-month", "id"],
                "unique_together": {("project", "month", "indicator")},
            },
        ),
    ]
