# Generated by Django 5.1.15 on 2026-08-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="文档标题")),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="requirements/",
                        verbose_name="原始文件",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="文件绝对路径",
                    ),
                ),
                (
                    "parsed_text",
                    models.TextField(
                        blank=True, default="", verbose_name="解析后的文本"
                    ),
                ),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI 完整度分析结果"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="是否确认入库"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求文档",
                "verbose_name_plural": "需求文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
