# Generated by Django 5.1.15 on 2026-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeitem",
            name="source",
            field=models.CharField(
                blank=True, default="manual", max_length=50, verbose_name="来源标记"
            ),
        ),
    ]
