# Generated by Django 5.1.15 on 2026-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
        ("project_planning", "0004_plantask"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklog",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="work_logs",
                to="project_planning.plantask",
                verbose_name="关联任务",
            ),
        ),
    ]
