# Generated by Django 5.1.15 on 2026-08-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="文档标题")),
                (
                    "doc_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="文档类型"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="文档内容(markdown)"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="delivery/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("agent", "Agent 回传"),
                            ("manual", "手动上传"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_docs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "交付文档",
                "verbose_name_plural": "交付文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
