# Generated by Django 5.1.15 on 2026-08-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="姓名"
            ),
        ),
    ]
