# Generated by Django 5.1.15 on 2026-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="capability",
            field=models.TextField(
                blank=True,
                default="",
                help_text="用于 AI 生成项目计划时参考，如擅长技术栈、可承担职责等",
                verbose_name="人员能力描述",
            ),
        ),
    ]
