# Generated by Django 5.1.15 on 2026-09-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_mcp_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginCaptcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, verbose_name="验证码")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("used", models.BooleanField(default=False, verbose_name="是否已使用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "登录验证码",
                "verbose_name_plural": "登录验证码",
            },
        ),
    ]
