# Generated by Django 5.1.15 on 2026-09-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_logincaptcha"),
    ]

    operations = [
        migrations.AddField(
            model_name="logincaptcha",
            name="fail_count",
            field=models.IntegerField(default=0, verbose_name="连续失败次数"),
        ),
    ]
